version: '3.8' # Can keep or remove, warning is harmless

services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # Persistent data volume
      - db_data:/var/lib/postgresql/data
      # Initialize schema on first run
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck: # Add healthcheck
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Give it a little time to start before checking
    networks:
      - app-network

  redis:
    image: redis:alpine
    volumes:
      # Persistent data volume
      - redis_data:/data
    networks:
      - app-network

  api:
    build: . # Build from local Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      # FIX: Correct Redis port to 6379
      REDIS_URL: redis://redis:6379/0
      CACHE_TTL_SECONDS: 300
      WEBHOOK_DELIVERY_TIMEOUT_SECONDS: 10
      CELERY_MAX_RETRIES: 7
      CELERY_BASE_RETRY_DELAY_SECONDS: 10
      LOG_RETENTION_HOURS: 72
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload # --reload for dev
    volumes:
      - ./app:/app/app # Mount code for easy development with --reload
    ports:
      - "8000:80" # Expose API to host on port 8000
    depends_on:
      db:
        condition: service_healthy # Wait for DB healthcheck
      redis:
        condition: service_started # Redis usually starts faster
    networks:
      - app-network

  worker:
    build: . # Build from local Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase 
      REDIS_URL: redis://redis:6379/0
      CACHE_TTL_SECONDS: 300
      WEBHOOK_DELIVERY_TIMEOUT_SECONDS: 10
      CELERY_MAX_RETRIES: 7
      CELERY_BASE_RETRY_DELAY_SECONDS: 10
      LOG_RETENTION_HOURS: 72
    command: celery -A app.celery_app worker -l info -P gevent # Use gevent for async IO
    volumes:
      - ./app:/app/app # Mount code
    depends_on:
      db:
        condition: service_healthy # Wait for DB healthcheck
      redis:
        condition: service_started
      api: # Depends on api (or db/redis)
        condition: service_started
    networks:
      - app-network

  beat:
    build: . # Build from local Dockerfile
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      REDIS_URL: redis://redis:6379/0
      LOG_RETENTION_HOURS: 72
    command: celery -A app.celery_app beat -l info # --scheduler ... if using external scheduler
    volumes:
      - ./app:/app/app # Mount code
    depends_on:
      db:
        condition: service_healthy # Wait for DB healthcheck
      redis:
        condition: service_started
    networks:
      - app-network

volumes:
  db_data: # Volume for PostgreSQL data persistence
  redis_data: # Volume for Redis data persistence

networks:
  app-network: # Define a custom network
    driver: bridge
